#!/bin/bash

# sudo ln ./start /etc/init.d/start_app
# sudo chmod +x /etc/init.d/start_app


for i in {1..10}
do
    echo "BoilerPI try to start n°$i"
    wget -q --tries=10 --timeout=20 --spider http://google.com
    if [[ $? -eq 0 ]];
        then
            echo "Raspberry Online"
            sudo rm -f /var/lib/mongodb/mongod.lock
            sudo service mongod restart
            NODE_ENV=raspberry forever start ./app.js
            break
        else
            echo "Raspberry pi Offline"
            sleep 1
    fi
done
